name = "pontocerto"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/public"

[[d1_databases]]
binding = "DB"
database_name = "pontocerto"
database_id = "e1eec67e-5c8a-4d6a-ac3a-af6daefddd1d"
